tasks:
  - before: | 
      curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      source $HOME/.poetry/env
    init: poetry install
    command: poetry run pytest
