import re
from typing import List

import click
from graphql.error import GraphQLError

# from strawberry.utils.sdl_transpiler import render_template
from strawberry.cli.commands.schema_importer import sdl_importer


@click.command("import-schema", short_help="Parses SDL file to strawberry types")
@click.argument("schema", type=str, required=True, nargs=-1)
def import_schema(schema):
    """ Parses SDL file to strawberry types and writes them out """
    strawberries = ""
    for s in schema:
        try:
            strawberries += sdl_importer.import_sdl(s)

        except FileNotFoundError:
            print(f"File not found on path: {s}")

        except GraphQLError:
            print(f"A file contains syntax errors {s}")

        finally:
            print("# Generated by strawberry")
            click.echo(strawberries)
