version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  deploy:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - add_ssh_keys
      - checkout
      - run: make check-has-release
      - run: make install-deploy-deps
      - run: make prepare-release
      - run: poetry build
      - run: make publish-changes
      - run: make create-github-release
      - run: poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD


workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
